export const root: string;
export const playerHeader: string;
export const cashAndNetHeader: string;
export const isPlayersTurn: string;
export const isPlayersMove: string;
export const player: string;
export const availableChainSizeAndPrice: string;
export const safeChain: string;
export const bottomRightCells: string;
