// this file was generated by running `yarn generateGameTestFilesSpec` and then formatting this file

import { runGameTestFile } from './runGameTestFile';

describe('game test files', () => {
    describe('start game', () => {
        it('it works', () => runGameTestFile('start game/it works.txt'));
    });
});
